import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:developer' as developer;
import '../models/phonics_game.dart';
import '../models/learner_profile.dart';
import '../utils/prompt_loader.dart';
import '../utils/service_locator.dart';
import 'global_session_manager.dart';

class AIPhonicsGenerationService {
  final Random _random = Random();
  final Map<String, Set<String>> _phonemeWordHistory = {};
  
  static final List<String> _allPhonemes = [
    // Basic consonants
    'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'w', 'y', 'z',
    // Vowels
    'a', 'e', 'i', 'o', 'u',
    // Digraphs
    'ch', 'sh', 'th', 'ph', 'wh', 'ng', 'ck',
    // Consonant blends
    'bl', 'br', 'cl', 'cr', 'dr', 'fl', 'fr', 'gl', 'gr', 'pl', 'pr', 'sc', 'sk', 'sl', 'sm', 'sn', 'sp', 'st', 'sw', 'tr', 'tw',
    // Vowel teams
    'ai', 'ay', 'ea', 'ee', 'ie', 'oa', 'oo', 'ou', 'ow'
  ];

  /// Generate dynamic sound sets based on learner profile
  Future<List<SoundSet>> generateGameSounds({
    required LearnerProfile? profile,
    int rounds = 5,
    int difficulty = 1,
  }) async {
    developer.log('🎯 Generating AI phonics content: rounds=$rounds, difficulty=$difficulty', 
        name: 'dyslexic_ai.phonics_ai');

    // 🔍 DIAGNOSTIC: Check if AI is available before starting
    final aiService = getAIInferenceService();
    if (aiService == null) {
      developer.log('🚨 CRITICAL: AI service is NULL - cannot generate phonics!', 
          name: 'dyslexic_ai.phonics_ai');
      throw Exception('AI service not available - model not initialized');
    } else {
      developer.log('✅ AI service is available - will attempt AI generation', 
          name: 'dyslexic_ai.phonics_ai');
    }

    try {
      // Analyze profile to determine focus areas
      final focusPhonemes = _extractFocusPhonemes(profile);
      final selectedPhonemes = _selectPhonemesForGame(focusPhonemes, rounds, difficulty);
      
      developer.log('📊 Selected phonemes: $selectedPhonemes', name: 'dyslexic_ai.phonics_ai');
      developer.log('🎯 Focus areas from profile: $focusPhonemes', name: 'dyslexic_ai.phonics_ai');

      // Pure AI generation (no fallbacks)
      developer.log('🤖 Generating all phonics content with AI (no fallbacks)...', 
          name: 'dyslexic_ai.phonics_ai');
          
      final batchSoundSets = await _generateAllPhonemesInBatch(
        selectedPhonemes,
        difficulty,
        profile,
      );
      
      developer.log('✅ USING AI-GENERATED CONTENT: ${batchSoundSets.length} sound sets from AI (100% AI)', 
          name: 'dyslexic_ai.phonics_ai');
      developer.log('🤖 AI SUCCESS: All phonics content generated by Gemma 3n model', 
          name: 'dyslexic_ai.phonics_ai');
      
      developer.log('🎉 Generated ${batchSoundSets.length} sound sets total', name: 'dyslexic_ai.phonics_ai');
      return batchSoundSets;

    } catch (e) {
      developer.log('❌ AI phonics generation failed: $e', name: 'dyslexic_ai.phonics_ai');
      throw Exception('Failed to generate phonics content with AI: $e');
    }
  }

  /// Extract focus phonemes from learner profile
  List<String> _extractFocusPhonemes(LearnerProfile? profile) {
    if (profile == null) return [];

    final focusPhonemes = <String>[];
    final focus = profile.focus.toLowerCase();

    // Analyze focus areas
    if (focus.contains('vowel')) {
      focusPhonemes.addAll(['a', 'e', 'i', 'o', 'u', 'ai', 'ay', 'ea', 'ee', 'ie', 'oa', 'oo']);
    }
    
    if (focus.contains('consonant') || focus.contains('blend')) {
      focusPhonemes.addAll(['bl', 'br', 'cl', 'cr', 'dr', 'fl', 'fr', 'gl', 'gr', 'pl', 'pr', 'sp', 'st', 'tr']);
    }
    
    if (focus.contains('digraph')) {
      focusPhonemes.addAll(['ch', 'sh', 'th', 'ph', 'wh', 'ng']);
    }

    // Add specific phonemes mentioned in profile
    for (final phoneme in _allPhonemes) {
      if (focus.contains(phoneme)) {
        focusPhonemes.add(phoneme);
      }
    }

    return focusPhonemes.toSet().toList(); // Remove duplicates
  }

  /// Select phonemes for game based on focus areas and difficulty
  List<String> _selectPhonemesForGame(List<String> focusPhonemes, int rounds, int difficulty) {
    final selectedPhonemes = <String>[];
    
    if (focusPhonemes.isNotEmpty) {
      // Emphasize focus areas (70% focus, 30% variety)
      final focusCount = (rounds * 0.7).round();
      final varietyCount = rounds - focusCount;
      
      // Add focus phonemes
      focusPhonemes.shuffle(_random);
      for (int i = 0; i < focusCount && i < focusPhonemes.length; i++) {
        selectedPhonemes.add(focusPhonemes[i]);
      }
      
      // Fill remaining with variety based on difficulty
      final varietyPhonemes = _getPhonemesForDifficulty(difficulty)
          .where((p) => !selectedPhonemes.contains(p))
          .toList();
      varietyPhonemes.shuffle(_random);
      
      for (int i = 0; i < varietyCount && i < varietyPhonemes.length; i++) {
        selectedPhonemes.add(varietyPhonemes[i]);
      }
    } else {
      // No specific focus - use difficulty-appropriate phonemes
      final availablePhonemes = _getPhonemesForDifficulty(difficulty);
      availablePhonemes.shuffle(_random);
      selectedPhonemes.addAll(availablePhonemes.take(rounds));
    }

    // Ensure we have enough phonemes
    while (selectedPhonemes.length < rounds) {
      final basicPhonemes = ['b', 'c', 'd', 'f', 'g'];
      selectedPhonemes.add(basicPhonemes[_random.nextInt(basicPhonemes.length)]);
    }

    selectedPhonemes.shuffle(_random); // Final shuffle for variety
    return selectedPhonemes.take(rounds).toList();
  }

  /// Get phonemes appropriate for difficulty level
  List<String> _getPhonemesForDifficulty(int difficulty) {
    switch (difficulty) {
      case 1: // Beginner
        return ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't'];
      case 2: // Intermediate  
        return ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'w', 'y', 'z', 'ch', 'sh', 'th'];
      case 3: // Advanced
        return _allPhonemes;
      default:
        return ['b', 'c', 'd', 'f', 'g'];
    }
  }



  /// Generate all phonemes in one batch (like sentence fixer does)
  Future<List<SoundSet>> _generateAllPhonemesInBatch(
    List<String> phonemes,
    int difficulty,
    LearnerProfile? profile,
  ) async {
    final aiService = getAIInferenceService();
    if (aiService == null) {
      developer.log('❌ AI service not available', name: 'dyslexic_ai.phonics_ai');
      throw Exception('AI service not available');
    }

    try {
      // Build prompt for all phonemes at once
      final prompt = await _buildBatchPrompt(phonemes, difficulty, profile);
      
      developer.log('📝 Batch AI generation for phonemes: $phonemes', name: 'dyslexic_ai.phonics_ai');

      // Single AI call for all phonemes (like sentence fixer)
      final response = await aiService.generateResponse(
        prompt,
        activity: AIActivity.phonicsGeneration,
      );

      developer.log('✅ Batch AI response received (${response.length} chars)', name: 'dyslexic_ai.phonics_ai');

      // Parse batch response
      final soundSets = _parseBatchResponse(response, phonemes, difficulty);
      
      developer.log('🎯 Parsed ${soundSets.length} sound sets from batch', name: 'dyslexic_ai.phonics_ai');
      
      return soundSets;

    } catch (e) {
      developer.log('❌ Batch generation failed: $e', name: 'dyslexic_ai.phonics_ai');
      rethrow;
    }
  }

  Future<String> _buildBatchPrompt(List<String> phonemes, int difficulty, LearnerProfile? profile) async {
    final difficultyLevel = _getDifficultyName(difficulty);
    final wordCount = _getWordCountForDifficulty(difficulty);
    
    final variables = <String, String>{
      'phoneme_count': phonemes.length.toString(),
      'difficulty_level': difficultyLevel,
      'incorrect_count': (wordCount - 1).toString(),
      'phonemes_list': phonemes.join(', '),
      'first_phoneme': phonemes.isNotEmpty ? phonemes[0] : 'b',
    };
    
    final template = await PromptLoader.load('phonics_generation', 'batch_generation.tmpl');
    return PromptLoader.fill(template, variables);
  }

  /// Parse batch response into sound sets
  List<SoundSet> _parseBatchResponse(String response, List<String> phonemes, int difficulty) {
    try {
      // Clean response to extract JSON
      String jsonStr = response.trim();
      
      // Remove markdown code blocks
      if (jsonStr.contains('```')) {
        final codeBlockMatch = RegExp(r'```(?:json)?\s*\n(.*?)\n\s*```', dotAll: true).firstMatch(jsonStr);
        if (codeBlockMatch != null) {
          jsonStr = codeBlockMatch.group(1)?.trim() ?? jsonStr;
        }
      }
      
      // Try to find JSON array
      final jsonMatch = RegExp(r'\[.*\]', dotAll: true).firstMatch(jsonStr);
      if (jsonMatch != null) {
        jsonStr = jsonMatch.group(0)!;
      }
      
      final List<dynamic> jsonArray = json.decode(jsonStr);
      final soundSets = <SoundSet>[];
      final allWordsUsed = <String>{};
      
      for (int i = 0; i < jsonArray.length && i < phonemes.length; i++) {
        final item = jsonArray[i];
        if (item is Map<String, dynamic>) {
          final phoneme = phonemes[i]; // Use expected phoneme order
          final soundSet = _createSoundSetFromBatchItem(item, phoneme, difficulty, i);
          if (soundSet != null) {
            // Check for global duplicates across all phonemes
            for (final wordOption in soundSet.words) {
              if (allWordsUsed.contains(wordOption.word.toLowerCase())) {
                developer.log('🚨 GLOBAL DUPLICATE: "${wordOption.word}" appears in multiple phonemes!', name: 'dyslexic_ai.phonics_ai');
              } else {
                allWordsUsed.add(wordOption.word.toLowerCase());
              }
            }
            
            soundSets.add(soundSet);
            developer.log('✅ Created sound set for: $phoneme', name: 'dyslexic_ai.phonics_ai');
          } else {
            developer.log('❌ Failed to create sound set for: $phoneme', name: 'dyslexic_ai.phonics_ai');
          }
        }
      }
      
      // Final summary of all words used
      developer.log('📋 TOTAL WORDS GENERATED: ${allWordsUsed.length} unique words across ${soundSets.length} phonemes', name: 'dyslexic_ai.phonics_ai');
      developer.log('📝 ALL WORDS: ${allWordsUsed.toList().join(', ')}', name: 'dyslexic_ai.phonics_ai');
      
      return soundSets;
      
    } catch (e) {
      developer.log('❌ Failed to parse batch response: $e', name: 'dyslexic_ai.phonics_ai');
      return [];
    }
  }

  /// Create sound set from batch item
  SoundSet? _createSoundSetFromBatchItem(Map<String, dynamic> item, String phoneme, int difficulty, int index) {
    try {
      final correctWords = (item['correct_words'] as List?)?.cast<String>() ?? [];
      final incorrectWords = (item['incorrect_words'] as List?)?.cast<String>() ?? [];
      final pronunciationHint = item['pronunciation_hint'] as String? ?? '';
      
      // Validate word distribution
      if (correctWords.length != 1) {
        developer.log('❌ Invalid correct word count for $phoneme: ${correctWords.length}', name: 'dyslexic_ai.phonics_ai');
        return null;
      }
      
      if (incorrectWords.length < 3) {
        developer.log('❌ Insufficient incorrect words for $phoneme: ${incorrectWords.length}', name: 'dyslexic_ai.phonics_ai');
        return null;
      }
      
      // Create word options
      final wordOptions = <WordOption>[];
      
      // Add correct word
      final correctWord = correctWords[0];
      wordOptions.add(WordOption(
        word: correctWord,
        imageUrl: '',
        isCorrect: true,
        phoneme: phoneme,
      ));
      
      // Add incorrect words
      final selectedIncorrectWords = incorrectWords.take(3).toList();
      for (final word in selectedIncorrectWords) {
        wordOptions.add(WordOption(
          word: word,
          imageUrl: '',
          isCorrect: false,
          phoneme: word.isNotEmpty ? word[0] : 'x',
        ));
      }
      
      // Log detailed word information BEFORE shuffling
      developer.log('🎯 PHONEME "$phoneme" WORDS:', name: 'dyslexic_ai.phonics_ai');
      developer.log('   ✅ CORRECT: "$correctWord" (starts with "$phoneme")', name: 'dyslexic_ai.phonics_ai');
      for (int i = 0; i < selectedIncorrectWords.length; i++) {
        final incorrectWord = selectedIncorrectWords[i];
        final actualStartingSound = incorrectWord.isNotEmpty ? incorrectWord[0].toLowerCase() : '?';
        developer.log('   ❌ INCORRECT ${i+1}: "$incorrectWord" (starts with "$actualStartingSound")', name: 'dyslexic_ai.phonics_ai');
      }
      
      // Validate no duplicates
      final allWords = [correctWord, ...selectedIncorrectWords];
      final uniqueWords = allWords.toSet();
      if (uniqueWords.length != allWords.length) {
        developer.log('⚠️ DUPLICATE WORDS DETECTED for phoneme "$phoneme": $allWords', name: 'dyslexic_ai.phonics_ai');
      }
      
      // Validate correct word matches phoneme rules
      if (_isValidPhonemeMatch(correctWord, phoneme)) {
        developer.log('✅ CORRECT WORD VALIDATED: "$correctWord" matches phoneme "$phoneme"', name: 'dyslexic_ai.phonics_ai');
      } else {
        developer.log('❌ WRONG CORRECT WORD: "$correctWord" does not match phoneme "$phoneme" rules', name: 'dyslexic_ai.phonics_ai');
      }
      
      // Shuffle word options to randomize answer position
      wordOptions.shuffle(_random);
      
      // Log final shuffled order
      developer.log('🔀 SHUFFLED ORDER for "$phoneme": ${wordOptions.map((w) => '${w.word}${w.isCorrect ? " (CORRECT)" : ""}').join(', ')}', name: 'dyslexic_ai.phonics_ai');
      
      return SoundSet(
        id: 'ai_batch_${phoneme}_$index',
        name: '${phoneme.toUpperCase()} Sounds',
        sound: _getPhonemeSound(phoneme),
        phoneme: phoneme,
        type: _getPhonemeType(phoneme),
        difficulty: difficulty,
        words: wordOptions,
        description: pronunciationHint.isNotEmpty ? pronunciationHint : _getStaticPronunciationHint(phoneme),
      );
      
    } catch (e) {
      developer.log('❌ Error creating sound set from batch item for $phoneme: $e', name: 'dyslexic_ai.phonics_ai');
      return null;
    }
  }


  /// Helper methods for phoneme properties
  String _getPhonemeSound(String phoneme) {
    final soundMap = {
      'b': 'buh', 'c': 'kuh', 'd': 'duh', 'f': 'fuh', 'g': 'guh',
      'ch': 'ch', 'sh': 'shh', 'th': 'th',
      // Add more as needed
    };
    return soundMap[phoneme] ?? '${phoneme}uh';
  }

  SoundType _getPhonemeType(String phoneme) {
    if (phoneme.length == 1 && 'aeiou'.contains(phoneme)) {
      return SoundType.vowel;
    } else if (phoneme.length > 1) {
      // Both consonant and vowel digraphs
      if (['ch', 'sh', 'th', 'ph', 'wh', 'ng', 'ck', 'ai', 'ay', 'ea', 'ee', 'ie', 'oa', 'ow', 'oo', 'ou', 'ue', 'ui'].contains(phoneme)) {
        return SoundType.digraph;
      } else {
        return SoundType.blend;
      }
    }
    return SoundType.consonant;
  }

  String _getStaticPronunciationHint(String phoneme) {
    final hintMap = {
      'b': 'Make the "buh" sound like in "ball"',
      'c': 'Make the "kuh" sound like in "cat"',
      'd': 'Make the "duh" sound like in "dog"',
      'ch': 'Put your tongue to the roof of your mouth and say "ch" like in "chair"',
      'sh': 'Put your finger to your lips and say "shh" like in "ship"',
      'th': 'Put your tongue between your teeth and say "th" like in "think"',
    };
    return hintMap[phoneme] ?? 'Practice the $phoneme sound';
  }

  String _getDifficultyName(int difficulty) {
    switch (difficulty) {
      case 1: return 'beginner';
      case 2: return 'intermediate';
      case 3: return 'advanced';
      default: return 'beginner';
    }
  }

  int _getWordCountForDifficulty(int difficulty) {
    switch (difficulty) {
      case 1: return 4; // 1 correct, 3 incorrect
      case 2: return 5; // 1 correct, 4 incorrect  
      case 3: return 6; // 1 correct, 5 incorrect
      default: return 4;
    }
  }

  /// Clear word history for a phoneme (useful for testing or reset)
  void clearWordHistory([String? phoneme]) {
    if (phoneme != null) {
      _phonemeWordHistory.remove(phoneme);
    } else {
      _phonemeWordHistory.clear();
    }
  }

  /// Get word generation statistics for debugging
  Map<String, int> getWordHistoryStats() {
    return _phonemeWordHistory.map((phoneme, words) => MapEntry(phoneme, words.length));
  }

  /// Validate if a word correctly matches the phoneme based on phoneme type
  bool _isValidPhonemeMatch(String word, String phoneme) {
    final cleanWord = word.toLowerCase();
    final cleanPhoneme = phoneme.toLowerCase();
    
    // Vowels: word should contain the vowel sound
    if (['a', 'e', 'i', 'o', 'u'].contains(cleanPhoneme)) {
      return cleanWord.contains(cleanPhoneme);
    }
    
    // Digraphs: word should start with the digraph
    if (['ch', 'sh', 'th', 'ph', 'wh', 'ng', 'ck'].contains(cleanPhoneme)) {
      return cleanWord.startsWith(cleanPhoneme);
    }
    
    // Consonants: word should start with the consonant
    return cleanWord.startsWith(cleanPhoneme);
  }
}